#!/usr/bin/env python3
"""Shared paths and constants for the AgentDoG-Lite preprocessing pipeline.

All paths resolve relative to the repository root so the pipeline is portable.
Override any path with the matching environment variable if your local layout
differs (e.g. AGENTDOG_TRAIN_DIR).
"""

from __future__ import annotations

import os
from pathlib import Path

# preprocessing/ -> repo root
REPO_ROOT = Path(__file__).resolve().parent.parent


def _env_path(name: str, default: Path) -> Path:
    value = os.environ.get(name)
    return Path(value).expanduser() if value else default


# --- Inputs -----------------------------------------------------------------
# AgentDoG 1.0 training data (the 8000-row raw pool). Lives outside the repo by
# default: D:/ailab/training data1.0/
TRAIN_DIR = _env_path("AGENTDOG_TRAIN_DIR", REPO_ROOT.parent / "training data1.0")
BINARY_FILE = TRAIN_DIR / "AgentDoG-BinarySafety" / "train.json"
FINEGRAINED_FILE = TRAIN_DIR / "AgentDoG-FineGrainedTaxonomy" / "train.json"

# Held-out evaluation sets (used ONLY for leakage checking, never for training).
TEST_DIR = _env_path("AGENTDOG_TEST_DIR", REPO_ROOT / "test case")
TEST_FILES = {
    "ATBench300": TEST_DIR / "summer_camp_ATBench300.json",
    "R-judge": TEST_DIR / "summer_camp_rjudge.json",
}

# --- Outputs ----------------------------------------------------------------
# Everything generated by the pipeline goes here (gitignored via outputs/).
OUTPUT_DIR = _env_path("AGENTDOG_OUTPUT_DIR", REPO_ROOT / "outputs" / "preprocessing")
STEP_DIRS = {
    "step0": OUTPUT_DIR / "step0_inventory",
    "step1": OUTPUT_DIR / "step1_dedup",
    "step2": OUTPUT_DIR / "step2_rules",
    "step3": OUTPUT_DIR / "step3_verify",
    "step4": OUTPUT_DIR / "step4_cot",
    "step5": OUTPUT_DIR / "step5_select",
    "scores": OUTPUT_DIR / "scores",
}


def ensure_dirs() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for path in STEP_DIRS.values():
        path.mkdir(parents=True, exist_ok=True)
